version: '1.1'
services:
  webgl:
    image: residuostecnologicos/Agau El protector del tiempo:latest
    container_name: Agau El protector del tiempo
    ports:
      - "8083:80"
    restart: always
